import { Wonder } from './types';

export const wondersData: Wonder[] = [
  {
    id: 'aurora_borealis_iceland',
    name: 'Aurora Borealis',
    location: 'Iceland',
    country: 'Iceland',
    category: 'Natural Wonders',
    description: 'Dancing lights painting the Arctic sky in brilliant green and purple hues',
    longDescription:
      'The Aurora Borealis, or Northern Lights, is one of nature\'s most spectacular displays. This celestial phenomenon occurs when electrically charged particles from the sun collide with gases in Earth\'s atmosphere, creating ethereal curtains of light that dance across the polar skies. Iceland offers some of the world\'s best viewing opportunities, with dark winter nights providing the perfect canvas for this cosmic masterpiece.',
    images: [
      'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=1200&q=80',
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&q=80',
      'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=1200&q=80',
    ],
    coordinates: { lat: 64.9631, lng: -19.0208 },
    bestVisitingMonths: ['September', 'October', 'February', 'March'],
    interestingFacts: [
      'Best viewed between September and April during dark, clear nights',
      'The lights can appear in various colors including green, pink, red, yellow, and blue',
      'Ancient Vikings believed the lights were reflections from the shields of the Valkyries',
      'The phenomenon occurs about 100 kilometers above Earth\'s surface',
    ],
    photographerCredits: ['Jonatan Pie', 'Vincent Guth', 'Kristin Wilson'],
    relatedWonders: ['machu_picchu_peru', 'antelope_canyon_arizona'],
  },
  {
    id: 'machu_picchu_peru',
    name: 'Machu Picchu',
    location: 'Cusco Region, Peru',
    country: 'Peru',
    category: 'Ancient Structures',
    description: 'Lost city of the Incas perched high in the Andean mountains',
    longDescription:
      'Machu Picchu stands as a testament to the architectural genius of the Inca civilization. Built in the 15th century and abandoned during the Spanish Conquest, this "Lost City" remained hidden for centuries until its rediscovery in 1911. Perched at 2,430 meters above sea level, the site features sophisticated dry-stone construction that has withstood centuries of earthquakes. The precise purpose of Machu Picchu remains a mystery, adding to its allure as one of the world\'s most iconic archaeological wonders.',
    images: [
      'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1200&q=80',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1200&q=80',
      'https://images.unsplash.com/photo-1587476258938-d7c7743f1b2a?w=1200&q=80',
    ],
    coordinates: { lat: -13.1631, lng: -72.545 },
    bestVisitingMonths: ['April', 'May', 'September', 'October'],
    interestingFacts: [
      'Built around 1450 at the height of the Inca Empire',
      'Contains over 150 buildings ranging from baths to temples',
      'Was never found by Spanish conquistadors during their rule',
      'Designated a UNESCO World Heritage Site in 1983',
      'Receives approximately 1.5 million visitors annually',
    ],
    historicalTimeline: [
      { year: '1450', event: 'Construction begins under Inca emperor Pachacuti' },
      { year: '1572', event: 'Abandoned during Spanish Conquest' },
      { year: '1911', event: 'Rediscovered by Hiram Bingham' },
      { year: '1983', event: 'Declared UNESCO World Heritage Site' },
    ],
    photographerCredits: ['Willian Justen', 'Pedro Lastra', 'David Mao'],
    relatedWonders: ['petra_jordan', 'bagan_temples_myanmar'],
  },
  {
    id: 'antelope_canyon_arizona',
    name: 'Antelope Canyon',
    location: 'Arizona, USA',
    country: 'United States',
    category: 'Geological Formations',
    description: 'Mesmerizing slot canyon with wave-like sandstone formations',
    longDescription:
      'Antelope Canyon is a photographer\'s paradise, featuring otherworldly sandstone formations carved by water over millions of years. Located on Navajo land near Page, Arizona, the canyon is divided into two sections: Upper Antelope Canyon (The Crack) and Lower Antelope Canyon (The Corkscrew). When sunlight filters through the narrow openings above, it creates ethereal beams of light that illuminate the flowing, wave-like walls in shades of orange, red, and purple. This natural wonder exemplifies the patient artistry of wind and water.',
    images: [
      'https://images.unsplash.com/photo-1444076953408-a4278aab0fbe?w=1200&q=80',
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    coordinates: { lat: 36.8619, lng: -111.3743 },
    bestVisitingMonths: ['March', 'April', 'May', 'September', 'October'],
    interestingFacts: [
      'The canyon was formed by flash flooding and erosion over millions of years',
      'Best light beams occur between March and October, particularly at midday',
      'The Navajo name is "Tsé bighánílíní" meaning "the place where water runs through rocks"',
      'Only accessible through guided tours to protect the sacred Navajo land',
      'Upper Antelope Canyon is more accessible and popular for light beam photography',
    ],
    photographerCredits: ['Ken Cheung', 'Naveen Kumar', 'Daniela Cuevas'],
    relatedWonders: ['aurora_borealis_iceland', 'zhangjiajie_china'],
  },
  {
    id: 'petra_jordan',
    name: 'Petra',
    location: 'Ma\'an Governorate, Jordan',
    country: 'Jordan',
    category: 'Ancient Structures',
    description: 'Rose-red city carved into towering cliffs by the Nabataeans',
    longDescription:
      'Petra, the "Rose City," is an archaeological marvel that seems to emerge from the very rock itself. Established around 300 BCE as the capital of the Nabataean Kingdom, this ancient city features elaborate buildings carved directly into rose-colored sandstone cliffs. The most famous structure, Al-Khazneh (The Treasury), greets visitors at the end of the narrow Siq canyon with its magnificent Hellenistic facade. Petra\'s sophisticated water management system and strategic location on ancient trade routes made it one of the most important cities of the ancient world.',
    images: [
      'https://images.unsplash.com/photo-1578271887552-5ac3a72752bc?w=1200&q=80',
      'https://images.unsplash.com/photo-1579966037165-e83c4f7c7289?w=1200&q=80',
      'https://images.unsplash.com/photo-1583151903300-6d2c2b37fddd?w=1200&q=80',
    ],
    coordinates: { lat: 30.3285, lng: 35.4444 },
    bestVisitingMonths: ['March', 'April', 'May', 'September', 'October', 'November'],
    interestingFacts: [
      'Petra was "rediscovered" in 1812 by Swiss explorer Johann Ludwig Burckhardt',
      'The city once housed over 20,000 people at its peak',
      'Featured prominently in the film "Indiana Jones and the Last Crusade"',
      'Contains over 800 carved monuments including tombs, temples, and elaborate facades',
      'Named one of the New Seven Wonders of the World in 2007',
    ],
    historicalTimeline: [
      { year: '312 BCE', event: 'First historical reference to Petra by the Nabataeans' },
      { year: '106 CE', event: 'Annexed by the Roman Empire' },
      { year: '663 CE', event: 'Islamic conquest begins' },
      { year: '1812', event: 'Rediscovered by Johann Ludwig Burckhardt' },
    ],
    photographerCredits: ['Simon Berger', 'Reiseuhu', 'Sander Crombach'],
    relatedWonders: ['machu_picchu_peru', 'angkor_wat_cambodia'],
  },
  {
    id: 'bagan_temples_myanmar',
    name: 'Bagan Temples',
    location: 'Mandalay Region, Myanmar',
    country: 'Myanmar',
    category: 'Ancient Structures',
    description: 'Thousands of ancient Buddhist pagodas dotting the plains at sunrise',
    longDescription:
      'The archaeological zone of Bagan contains over 2,000 surviving Buddhist monuments spread across 26 square miles of plains along the Ayeyarwady River. Built between the 11th and 13th centuries when Bagan was the capital of the Pagan Kingdom, these temples and stupas represent one of the world\'s greatest concentrations of Buddhist architecture. At sunrise, hot air balloons float over the misty plains as the golden light illuminates countless spires and domes, creating one of Southeast Asia\'s most breathtaking panoramas.',
    images: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&q=80',
      'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=1200&q=80',
      'https://images.unsplash.com/photo-1570366583862-f91883984fde?w=1200&q=80',
    ],
    coordinates: { lat: 21.1717, lng: 94.8586 },
    bestVisitingMonths: ['November', 'December', 'January', 'February'],
    interestingFacts: [
      'Over 10,000 temples were originally built in Bagan during its golden age',
      'The temples were constructed over a 250-year period',
      'Hot air balloon rides at sunrise are a popular way to view the temples',
      'Designated a UNESCO World Heritage Site in 2019',
      'Some temples feature exquisite interior murals depicting Buddhist stories',
    ],
    historicalTimeline: [
      { year: '1057', event: 'King Anawrahta begins temple construction program' },
      { year: '1287', event: 'Mongol invasion leads to decline of Bagan' },
      { year: '1975', event: 'Devastating earthquake damages many temples' },
      { year: '2019', event: 'Inscribed as UNESCO World Heritage Site' },
    ],
    photographerCredits: ['Gianluca Mancini', 'Timo Stern', 'Clay Banks'],
    relatedWonders: ['angkor_wat_cambodia', 'petra_jordan'],
  },
  {
    id: 'zhangjiajie_china',
    name: 'Zhangjiajie Pillars',
    location: 'Hunan Province, China',
    country: 'China',
    category: 'Geological Formations',
    description: 'Towering sandstone pillars that inspired the floating mountains of Avatar',
    longDescription:
      'The Zhangjiajie National Forest Park features over 3,000 towering quartzite sandstone pillars that rise dramatically from the forest floor, some reaching heights of over 200 meters. These spectacular formations were created over millions of years through erosion and weathering. The park gained international fame after inspiring the floating Hallelujah Mountains in James Cameron\'s film "Avatar." Mist frequently envelops the peaks, creating an otherworldly landscape that has captivated poets and artists for centuries.',
    images: [
      'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1200&q=80',
      'https://images.unsplash.com/photo-1537890992284-c81c2b5e4f23?w=1200&q=80',
      'https://images.unsplash.com/photo-1586655852132-93c8e2026fae?w=1200&q=80',
    ],
    coordinates: { lat: 29.3167, lng: 110.4794 },
    bestVisitingMonths: ['April', 'May', 'September', 'October'],
    interestingFacts: [
      'China\'s first national forest park, established in 1982',
      'One pillar was renamed "Avatar Hallelujah Mountain" in honor of the film',
      'The park features the world\'s longest and highest glass bridge',
      'Home to over 500 species of animals and 3,000 species of plants',
      'UNESCO World Heritage Site as part of Wulingyuan Scenic Area',
    ],
    photographerCredits: ['Robert Nyman', 'Nikolay Vorobyev', 'Yang Shuo'],
    relatedWonders: ['antelope_canyon_arizona', 'grand_canyon_arizona'],
  },
  {
    id: 'victoria_falls',
    name: 'Victoria Falls',
    location: 'Zimbabwe/Zambia Border',
    country: 'Zimbabwe',
    category: 'Natural Wonders',
    description: 'The world\'s largest curtain of falling water with thundering cascades',
    longDescription:
      'Victoria Falls is the largest curtain of falling water in the world, measuring 1,708 meters wide and 108 meters high. Known locally as "Mosi-oa-Tunya" (The Smoke That Thunders), the falls create a spray visible from 50 kilometers away. During peak flow, over 500 million liters of water plunge over the edge every minute, creating a perpetual mist that sustains a unique rainforest ecosystem. The falls\' combination of width and height makes it one of the most impressive waterfalls on Earth.',
    images: [
      'https://images.unsplash.com/photo-1484318571209-661cf29a69c3?w=1200&q=80',
      'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200&q=80',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80',
    ],
    coordinates: { lat: -17.9243, lng: 25.8572 },
    bestVisitingMonths: ['February', 'March', 'April', 'May'],
    interestingFacts: [
      'Named by David Livingstone after Queen Victoria of England in 1855',
      'During peak flow, the spray can rise over 400 meters high',
      'The Devil\'s Pool at the edge allows brave swimmers to peer over during dry season',
      'A UNESCO World Heritage Site since 1989',
      'The falls are slowly eroding upstream, having moved 8 kilometers over time',
    ],
    photographerCredits: ['Davidova Dmitri', 'Hu Chen', 'Tobias Reich'],
    relatedWonders: ['iguazu_falls', 'niagara_falls'],
  },
  {
    id: 'great_barrier_reef',
    name: 'Great Barrier Reef',
    location: 'Queensland, Australia',
    country: 'Australia',
    category: 'Natural Wonders',
    description: 'The world\'s largest coral reef system teeming with marine life',
    longDescription:
      'The Great Barrier Reef is the largest living structure on Earth, stretching over 2,300 kilometers along Australia\'s northeastern coast. This magnificent ecosystem comprises 2,900 individual reefs and 900 islands, home to an astounding diversity of marine life including 1,500 fish species, 400 coral species, and countless other organisms. Visible from space, the reef is a natural wonder of stunning beauty, featuring vibrant coral gardens, crystal-clear waters, and an underwater world that has captivated explorers and scientists for generations.',
    images: [
      'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=1200&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200&q=80',
    ],
    coordinates: { lat: -18.2871, lng: 147.6992 },
    bestVisitingMonths: ['June', 'July', 'August', 'September', 'October'],
    interestingFacts: [
      'Supports approximately 10% of the world\'s total fish species',
      'The reef structure has been forming for over 20 million years',
      'Home to six species of sea turtles and 30 species of whales and dolphins',
      'Provides $6.4 billion annually to the Australian economy',
      'Listed as a UNESCO World Heritage Site in 1981',
    ],
    photographerCredits: ['Dan Pham', 'Francesco Ungaro', 'David Clode'],
    relatedWonders: ['blue_hole_belize', 'maldives_reefs'],
  },
  {
    id: 'santorini_greece',
    name: 'Santorini',
    location: 'Cyclades, Greece',
    country: 'Greece',
    category: 'Cultural Sites',
    description: 'Iconic white-washed villages perched on volcanic cliffs above the Aegean',
    longDescription:
      'Santorini is a crescent-shaped volcanic island in the Aegean Sea, famous for its dramatic cliffs crowned with gleaming white buildings and blue-domed churches. The island was shaped by one of history\'s most powerful volcanic eruptions around 1600 BCE, which created the stunning caldera that defines its landscape today. The villages of Oia and Fira offer some of the world\'s most photographed sunsets, where golden light bathes the white architecture and illuminates the deep blue waters below. This iconic Greek island combines natural beauty with rich history and timeless Mediterranean charm.',
    images: [
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80',
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80',
      'https://images.unsplash.com/photo-1560107048-da06e5a84c35?w=1200&q=80',
    ],
    coordinates: { lat: 36.3932, lng: 25.4615 },
    bestVisitingMonths: ['April', 'May', 'September', 'October'],
    interestingFacts: [
      'The volcanic eruption that shaped Santorini may have inspired Atlantis legends',
      'The island produces unique wines from grapes grown in volcanic soil',
      'Oia is considered one of the best places in the world to watch sunsets',
      'The white buildings reflect heat, keeping interiors cool in summer',
      'Ancient Akrotiri, a Minoan Bronze Age settlement, is preserved under volcanic ash',
    ],
    photographerCredits: ['Valeriia Miller', 'Jimmy Teoh', 'Spencer Davis'],
    relatedWonders: ['amalfi_coast_italy', 'cinque_terre_italy'],
  },
  {
    id: 'angkor_wat_cambodia',
    name: 'Angkor Wat',
    location: 'Siem Reap, Cambodia',
    country: 'Cambodia',
    category: 'Ancient Structures',
    description: 'Magnificent temple complex and largest religious monument in the world',
    longDescription:
      'Angkor Wat is the crown jewel of Khmer architecture and the largest religious monument ever constructed. Built in the 12th century by King Suryavarman II, this massive temple complex was originally dedicated to the Hindu god Vishnu before gradually transforming into a Buddhist temple. The site covers 162.6 hectares and features intricate bas-reliefs, towering spires meant to represent Mount Meru (the home of the gods), and a sophisticated system of canals and reservoirs. At sunrise, the temple\'s silhouette reflects in the surrounding pools, creating one of Asia\'s most iconic and photographed scenes.',
    images: [
      'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1200&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80',
      'https://images.unsplash.com/photo-1563184277-d83d4d9fe4fa?w=1200&q=80',
    ],
    coordinates: { lat: 13.4125, lng: 103.8670 },
    bestVisitingMonths: ['November', 'December', 'January', 'February'],
    interestingFacts: [
      'Construction required more stone than all the Egyptian pyramids combined',
      'The temple is designed to represent the Hindu universe in stone',
      'Features over 3,000 Apsara (celestial dancer) carvings, no two alike',
      'The central tower rises 65 meters above ground level',
      'Appears on Cambodia\'s national flag',
    ],
    historicalTimeline: [
      { year: '1113', event: 'Construction begins under King Suryavarman II' },
      { year: '1432', event: 'Khmer empire declines, Angkor largely abandoned' },
      { year: '1860', event: 'French naturalist Henri Mouhot brings site to Western attention' },
      { year: '1992', event: 'Designated UNESCO World Heritage Site' },
    ],
    photographerCredits: ['Florian Wehde', 'Marvin Meyer', 'Josh Hild'],
    relatedWonders: ['bagan_temples_myanmar', 'borobudur_indonesia'],
  },
];
